### ISSUE TITLE
激活失败

### ISSUE THREAD

**Issue by moroal** [TimeShining/Android-Dev-Tools#13]
我买了激活码，可是有一部手机提示激活失败，必须在Google Play激活，为什么呢？怎么解决呢？

**Comment by Trinea** [comment]
Google Play 版和国内版不一样，Google Play 版本无法使用激活码，可以从 https://coolapk.com/apk/cn.trinea.android.developertools 下载国内版

**Comment by moroal** [comment]
是从这儿下载的哦，只不过同一个apk，有一台手机提示激活成功，有一台说必须在Google Play激活

**Comment by Trinea** [comment]
感谢，方便的话可以加下微信 TimeMeasurer 帮详细介绍下情况
