### ISSUE TITLE
No pro version check if the action is started from the quick access/settings menu

### ISSUE THREAD

**Issue by Tosch-IT** [TimeShining/Android-Dev-Tools#20]
If the pro version is obtained by an in-app buy, pro actions can still not be started from the quick access/settings menu if the app is closed.
Instead, the error message "This is a pro feature. You need to upgrade to pro version" is shown.

**Comment by Flybyflyhigh** [comment]
https://github.com/TimeShining/Android-Dev-Tools/issues/20#issue-1028386597

**Comment by Trinea** [comment]
Yes, this is a bug due to avoid the app is be hacked
