### ISSUE TITLE
更新12之后屏幕上出现一个悬浮球

### ISSUE THREAD

**Issue by Zheng-Shuo** [TimeShining/Android-Dev-Tools#21]
如下图，更新12系统之后就出现了，我该如何隐藏它，谢谢
![Screenshot_20211027-112145~2](https://user-images.githubusercontent.com/21071040/138994805-1453a627-3e71-4f29-914e-acc87d499aea.png)

**Comment by Trinea** [comment]
这个问题的解决方案可见： https://codekk.com/developer-tools/faq#xiaomi-screen-right-bottom-corner-float-ball

**Comment by Trinea** [comment]
这个问题的解决方案可见： https://codekk.com/developer-tools/faq#xiaomi-screen-right-bottom-corner-float-ball
