### ISSUE TITLE
Samsung Galaxy J7 P

### ISSUE THREAD

**Issue by TQuocBao86** [TimeShining/Android-Dev-Tools#3]
Model: SM-G975F
Manufacturer: samsung
Board: exynos9820
Device: beyond2
Product: beyond2lteeea
CPU Cores: 8
CPU Bit: 64-Bit
Memory: Total 7.23 GB, Avail 3.0 GB
Storage: Total 109.93 GB, Avail 76.83 GB
Resolution: 1080 * 2280 px / 420 dp
Screen Size: 2.7" * 5.8" / 6.4 Inches

Android 10 / API 29
Baseband Version: G975FXXS3BSL4,G975FXXS3BSL4
Build Number: QP1A.190711.020.G975FXXS3BSL4
Linux Kernel Version: 4.14.113-17369399
Http User Agent: Dalvik/2.1.0 (Linux; U; Android 10; SM-G975F Build/QP1A.190711.020)

Thank you!

On Thu, Feb 20, 2020 at 5:45 PM +0100, "Trinea" <notifications@github.com> wrote:

Can you tell me which button do you have clicked? and what's your phone model and Android  version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @Losto88 in https://github.com/TimeShining/Android-Dev-Tools/issues/1#issuecomment-589235918_

**Comment by quocbao38** [comment]
> Model: SM-G975F
> Manufacturer: samsung
> Board: exynos9820
> Device: beyond2
> Product: beyond2lteeea
> CPU Cores: 8
> CPU Bit: 64-Bit
> Memory: Total 7.23 GB, Avail 3.0 GB
> Storage: Total 109.93 GB, Avail 76.83 GB
> Resolution: 1080 * 2280 px / 420 dp
> Screen Size: 2.7" * 5.8" / 6.4 Inches
> 
> Android 10 / API 29
> Baseband Version: G975FXXS3BSL4,G975FXXS3BSL4
> Build Number: QP1A.190711.020.G975FXXS3BSL4
> Linux Kernel Version: 4.14.113-17369399
> Http User Agent: Dalvik/2.1.0 (Linux; U; Android 10; SM-G975F Build/QP1A.190711.020)
> 
> Thank you!
>

**Comment by TQuocBao86** [comment]
> Model: SM-G975F
> Manufacturer: samsung
> Board: exynos9820
> Device: beyond2
> Product: beyond2lteeea
> CPU Cores: 8
> CPU Bit: 64-Bit
> Memory: Total 7.23 GB, Avail 3.0 GB
> Storage: Total 109.93 GB, Avail 76.83 GB
> Resolution: 1080 * 2280 px / 420 dp
> Screen Size: 2.7" * 5.8" / 6.4 Inches
> 
> Android 10 / API 29
> Baseband Version: G975FXXS3BSL4,G975FXXS3BSL4
> Build Number: QP1A.190711.020.G975FXXS3BSL4
> Linux Kernel Version: 4.14.113-17369399
> Http User Agent: Dalvik/2.1.0 (Linux; U; Android 10; SM-G975F Build/QP1A.190711.020)
> 
> 
> 
> 
> Thank you!
> 
> 
>
