### ISSUE TITLE
无法使用布局查看

### ISSUE THREAD

**Issue by huhao1987** [TimeShining/Android-Dev-Tools#55]
布局查看有时完全不显示任何内容，有时候会显示一次当前activity，但切换到其他应用不会改变，点击下载按钮完全没反应，然后过会弹出了内存溢出的错误，我也是搞开发，所以用了异常跟踪。手机是一加11 Android14
![Screenshot_2024-05-10-08-11-17-19_2e9554f8be571263c1dd340a785e4ddf.jpg](https://github.com/TimeShining/Android-Dev-Tools/assets/9996556/072e5d4d-7f29-4afe-b183-295b979d7764)

**Comment by Trinea** [comment]
收到，感谢反馈并提供堆栈。请问这个开发助手版本是多少？

**Comment by Trinea** [comment]
最新 8.0.0 版已经支持多 tab 切换、滚动页面的布局查看功能，可从国内各大市场下载使用
