### ISSUE TITLE
root开启无障碍

### ISSUE THREAD

**Issue by fxynb399** [TimeShining/Android-Dev-Tools#57]
希望加入这个一键开启，一般用这个的手机都有root，希望加入一键开启，不然有时候操作真的很麻烦。

**Comment by Trinea** [comment]
感谢反馈，这个功能会在 8.0.0 版加入。预计下周会发布

**Comment by Trinea** [comment]
最新 8.0.0 版已支持 root 手机上一键开启无障碍服务，可从国内各大市场下载使用

**Comment by fxynb399** [comment]
幸苦大佬了&nbsp;


道无涯i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月27日(星期二) 晚上11:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TimeShining/Android-Dev-Tools] root开启无障碍 (Issue #57)














 
最新 8.0.0 版已支持 root 手机上一键开启无障碍服务，可从国内各大市场下载使用
